/*
 * Copyright (C) 2014 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef INTEL_CAMERA_METADATA_TAGS_H
#define INTEL_CAMERA_METADATA_TAGS_H
#include <system/camera_metadata.h>

/**
 * ! Do not edit this file directly !
 *
 * Generated automatically from intel_camera_metadata_tags.mako
 */

/** TODO: Nearly every enum in this file needs a description */

/**
 * Top level hierarchy definitions for camera metadata. *_INFO sections are for
 * the static metadata that can be retrived without opening the camera device.
 * New sections must be added right before INTEL_DEPTH_SECTION_COUNT to maintain
 * existing enumerations.
 */
typedef enum intel_camera_metadata_section {
    INTEL_AIQ,
    INTEL_FACE_ENGINE,
    INTEL_FACE_ENGINE_INFO,
    INTEL_DS4,
    INTEL_DEPTHCOMMON,
    INTEL_CAMERA_SECTION_COUNT,
} intel_camera_metadata_section_t;

/**
 * Hierarchy positions in enum space. All vendor extension tags must be
 * defined with tag >= VENDOR_SECTION_START
 */
typedef enum intel_camera_metadata_section_start {
    INTEL_AIQ_START                = (INTEL_AIQ                << 16 ) | VENDOR_SECTION_START,
    INTEL_FACE_ENGINE_START        = (INTEL_FACE_ENGINE        << 16 ) | VENDOR_SECTION_START,
    INTEL_FACE_ENGINE_INFO_START   = (INTEL_FACE_ENGINE_INFO   << 16 ) | VENDOR_SECTION_START,
    INTEL_DS4_START                = (INTEL_DS4                << 16 ) | VENDOR_SECTION_START,
    INTEL_DEPTHCOMMON_START        = (INTEL_DEPTHCOMMON        << 16 ) | VENDOR_SECTION_START,
} intel_camera_metadata_section_start_t;

/**
 * Main enum for defining camera metadata tags.  New entries must always go
 * before the section _END tag to preserve existing enumeration values.  In
 * addition, the name and type of the tag needs to be added to
 * src/intel_camera_metadata_tag_info.c
 */
typedef enum intel_camera_metadata_tag {
    COM_INTEL_AIQ_ANALYSIS_MODE =                     // enum         | public
            INTEL_AIQ_START,
    COM_INTEL_AIQ_MULTI_FRAME_HINT,                   // enum         | public
    COM_INTEL_AIQ_SCENE_DETECTED,                     // enum         | public
    INTEL_AIQ_END,

    COM_INTEL_FACE_ENGINE_SMILE_DETECT_MODE =         // enum         | public
            INTEL_FACE_ENGINE_START,
    COM_INTEL_FACE_ENGINE_SMILE_DETECT_STATUS,        // byte[]       | public
    COM_INTEL_FACE_ENGINE_SMILE_DETECT_SCORES,        // int32[]      | public
    COM_INTEL_FACE_ENGINE_FACE_DETECT_RIP_ANGLES,     // int32[]      | public
    INTEL_FACE_ENGINE_END,

    COM_INTEL_FACE_ENGINE_INFO_AVAILABLE_SMILE_DETECT = 
                                                      // byte[]       | public
            INTEL_FACE_ENGINE_INFO_START,
    COM_INTEL_FACE_ENGINE_INFO_AVAILABLE_BLINK_DETECT,// byte[]       | public
    COM_INTEL_FACE_ENGINE_INFO_AVAILABLE_FACE_RECOGNIZE,
                                                      // byte[]       | public
    COM_INTEL_FACE_ENGINE_INFO_AVAILABLE_OBJECT_TRACK,// byte[]       | public
    COM_INTEL_FACE_ENGINE_INFO_AVAILABLE_PANORAMA,    // byte[]       | public
    INTEL_FACE_ENGINE_INFO_END,

    COM_INTEL_DS4_MEDIAN_THRESHOLD =                  // int32        | public
            INTEL_DS4_START,
    COM_INTEL_DS4_SCORE_MIN_THRESHOLD,                // int32        | public
    COM_INTEL_DS4_SCORE_MAX_THRESHOLD,                // int32        | public
    COM_INTEL_DS4_NEIGHBOR_THRESHOLD,                 // int32        | public
    COM_INTEL_DS4_LR_AGREE_THRESHOLD,                 // int32        | public
    COM_INTEL_DS4_TEXTURE_COUNT_THRESHOLD,            // int32        | public
    COM_INTEL_DS4_TEXTURE_DIFFERENCE_THRESHOLD,       // int32        | public
    COM_INTEL_DS4_SECOND_PEAK_THRESHOLD,              // int32        | public
    COM_INTEL_DS4_RGB_RECTIFICATION_MODE,             // enum         | public
    INTEL_DS4_END,

    COM_INTEL_DEPTHCOMMON_DEPTH_UNITS =               // enum         | public
            INTEL_DEPTHCOMMON_START,
    COM_INTEL_DEPTHCOMMON_DISPARITY_OUTPUT_MODE,      // enum         | public
    COM_INTEL_DEPTHCOMMON_DISPARITY_MULTIPLIER,       // double       | public
    COM_INTEL_DEPTHCOMMON_DEPTH_MIN,                  // int32        | public
    COM_INTEL_DEPTHCOMMON_DEPTH_MAX,                  // int32        | public
    COM_INTEL_DEPTHCOMMON_EMITTER,                    // enum         | public
    COM_INTEL_DEPTHCOMMON_NODE_EXPOSURE_TIME,         // int64[]      | public
    COM_INTEL_DEPTHCOMMON_NODE_AE_MODE,               // enum[]       | public
    COM_INTEL_DEPTHCOMMON_NODE_GAIN_FACTOR,           // rational[]   | public
    COM_INTEL_DEPTHCOMMON_NODE_FRAME_COUNTERS_MODE,   // enum         | public
    COM_INTEL_DEPTHCOMMON_FRAME_SYNC_MODE,            // enum         | public
    COM_INTEL_DEPTHCOMMON_MODULE_ID,                  // enum         | public
    COM_INTEL_DEPTHCOMMON_CALIBRATION_DATA,           // byte[]       | public
    COM_INTEL_DEPTHCOMMON_AVAILABLE_DEPTH_UNITS,      // byte[]       | public
    COM_INTEL_DEPTHCOMMON_AVAILABLE_NODES,            // enum[]       | public
    COM_INTEL_DEPTHCOMMON_SIZE_NODES_MAPPING,         // byte[]       | public
    COM_INTEL_DEPTHCOMMON_FORMAT_NODES_MAPPING,       // byte[]       | public
    COM_INTEL_DEPTHCOMMON_NODE_EXPOSURE_TIME_RANGE,   // int64[]      | public
    COM_INTEL_DEPTHCOMMON_NODE_GAIN_RANGE,            // int64[]      | public
    COM_INTEL_DEPTHCOMMON_NODE_FRAME_COUNTERS,        // int32[]      | public
    INTEL_DEPTHCOMMON_END,

} intel_camera_metadata_tag_t;

/**
 * Enumeration definitions for the various entries that need them
 */

// COM_INTEL_AIQ_ANALYSIS_MODE
typedef enum intel_camera_metadata_enum_com_intel_aiq_analysis_mode {
    COM_INTEL_AIQ_ANALYSIS_MODE_OFF,
    COM_INTEL_AIQ_ANALYSIS_MODE_ON,
} intel_camera_metadata_enum_com_intel_aiq_analysis_mode_t;

// COM_INTEL_AIQ_MULTI_FRAME_HINT
typedef enum intel_camera_metadata_enum_com_intel_aiq_multi_frame_hint {
    COM_INTEL_AIQ_MULTI_FRAME_HINT_NONE,
    COM_INTEL_AIQ_MULTI_FRAME_HINT_ULL,
    COM_INTEL_AIQ_MULTI_FRAME_HINT_HDR,
} intel_camera_metadata_enum_com_intel_aiq_multi_frame_hint_t;

// COM_INTEL_AIQ_SCENE_DETECTED
typedef enum intel_camera_metadata_enum_com_intel_aiq_scene_detected {
    COM_INTEL_AIQ_SCENE_DETECTED_NONE,
    COM_INTEL_AIQ_SCENE_DETECTED_CLOSE_UP_PORTRAIT,
    COM_INTEL_AIQ_SCENE_DETECTED_PORTRAIT,
    COM_INTEL_AIQ_SCENE_DETECTED_LOWLIGHT_PORTRAIT,
    COM_INTEL_AIQ_SCENE_DETECTED_LOWLIGHT,
    COM_INTEL_AIQ_SCENE_DETECTED_ACTION,
    COM_INTEL_AIQ_SCENE_DETECTED_BACKLIGHT,
    COM_INTEL_AIQ_SCENE_DETECTED_LANDSCAPE,
    COM_INTEL_AIQ_SCENE_DETECTED_DOCUMENT,
    COM_INTEL_AIQ_SCENE_DETECTED_FIREWORK,
    COM_INTEL_AIQ_SCENE_DETECTED_LOWLIGHT_ACTION,
    COM_INTEL_AIQ_SCENE_DETECTED_BABY,
    COM_INTEL_AIQ_SCENE_DETECTED_BARCODE,
} intel_camera_metadata_enum_com_intel_aiq_scene_detected_t;


// COM_INTEL_FACE_ENGINE_SMILE_DETECT_MODE
typedef enum intel_camera_metadata_enum_com_intel_face_engine_smile_detect_mode {
    COM_INTEL_FACE_ENGINE_SMILE_DETECT_MODE_OFF,
    COM_INTEL_FACE_ENGINE_SMILE_DETECT_MODE_ON,
} intel_camera_metadata_enum_com_intel_face_engine_smile_detect_mode_t;



// COM_INTEL_DS4_RGB_RECTIFICATION_MODE
typedef enum intel_camera_metadata_enum_com_intel_ds4_rgb_rectification_mode {
    COM_INTEL_DS4_RGB_RECTIFICATION_MODE_OFF,
    COM_INTEL_DS4_RGB_RECTIFICATION_MODE_ON,
} intel_camera_metadata_enum_com_intel_ds4_rgb_rectification_mode_t;


// COM_INTEL_DEPTHCOMMON_DEPTH_UNITS
typedef enum intel_camera_metadata_enum_com_intel_depthcommon_depth_units {
    COM_INTEL_DEPTHCOMMON_DEPTH_UNITS_MICRON,
    COM_INTEL_DEPTHCOMMON_DEPTH_UNITS_MM,
} intel_camera_metadata_enum_com_intel_depthcommon_depth_units_t;

// COM_INTEL_DEPTHCOMMON_DISPARITY_OUTPUT_MODE
typedef enum intel_camera_metadata_enum_com_intel_depthcommon_disparity_output_mode {
    COM_INTEL_DEPTHCOMMON_DISPARITY_OUTPUT_MODE_OFF,
    COM_INTEL_DEPTHCOMMON_DISPARITY_OUTPUT_MODE_ON,
} intel_camera_metadata_enum_com_intel_depthcommon_disparity_output_mode_t;

// COM_INTEL_DEPTHCOMMON_EMITTER
typedef enum intel_camera_metadata_enum_com_intel_depthcommon_emitter {
    COM_INTEL_DEPTHCOMMON_EMITTER_OFF,
    COM_INTEL_DEPTHCOMMON_EMITTER_ON,
} intel_camera_metadata_enum_com_intel_depthcommon_emitter_t;

// COM_INTEL_DEPTHCOMMON_NODE_AE_MODE
typedef enum intel_camera_metadata_enum_com_intel_depthcommon_node_ae_mode {
    COM_INTEL_DEPTHCOMMON_NODE_AE_MODE_OFF,
    COM_INTEL_DEPTHCOMMON_NODE_AE_MODE_ON,
} intel_camera_metadata_enum_com_intel_depthcommon_node_ae_mode_t;

// COM_INTEL_DEPTHCOMMON_NODE_FRAME_COUNTERS_MODE
typedef enum intel_camera_metadata_enum_com_intel_depthcommon_node_frame_counters_mode {
    COM_INTEL_DEPTHCOMMON_NODE_FRAME_COUNTERS_MODE_OFF,
    COM_INTEL_DEPTHCOMMON_NODE_FRAME_COUNTERS_MODE_ON,
} intel_camera_metadata_enum_com_intel_depthcommon_node_frame_counters_mode_t;

// COM_INTEL_DEPTHCOMMON_FRAME_SYNC_MODE
typedef enum intel_camera_metadata_enum_com_intel_depthcommon_frame_sync_mode {
    COM_INTEL_DEPTHCOMMON_FRAME_SYNC_MODE_OFF,
    COM_INTEL_DEPTHCOMMON_FRAME_SYNC_MODE_ON,
} intel_camera_metadata_enum_com_intel_depthcommon_frame_sync_mode_t;

// COM_INTEL_DEPTHCOMMON_MODULE_ID
typedef enum intel_camera_metadata_enum_com_intel_depthcommon_module_id {
    COM_INTEL_DEPTHCOMMON_MODULE_ID_DS,
    COM_INTEL_DEPTHCOMMON_MODULE_ID_IVCAM,
} intel_camera_metadata_enum_com_intel_depthcommon_module_id_t;

// COM_INTEL_DEPTHCOMMON_AVAILABLE_NODES
typedef enum intel_camera_metadata_enum_com_intel_depthcommon_available_nodes {
    COM_INTEL_DEPTHCOMMON_AVAILABLE_NODES_COLOR,
    COM_INTEL_DEPTHCOMMON_AVAILABLE_NODES_DEPTH,
    COM_INTEL_DEPTHCOMMON_AVAILABLE_NODES_LEFT_RIGHT,
    COM_INTEL_DEPTHCOMMON_AVAILABLE_NODES_CENTER,
} intel_camera_metadata_enum_com_intel_depthcommon_available_nodes_t;


#endif
